force-app/main/default/objects/Manage_Data_Group__c/Manage_Data_Group__c.object-meta.xml
<CustomObject>
    <label>Manage Data Group</label>
    <nameField>
        <label>Manage Data Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Data Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Data_Object__c/Manage_Data_Object__c.object-meta.xml
<CustomObject>
    <label>Manage Data Object</label>
    <nameField>
        <label>Manage Data Objects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Data Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Data_Object__c/fields/Allowed_Operations__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Operations__c</fullName>
    <label>Allowed Operations</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Data_Object__c/fields/Manage_Data_Group__c.field-meta.xml
<CustomField>
    <fullName>Manage_Data_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Manage Data Group</label>
    <referenceTo>Manage_Data_Group__c</referenceTo>
    <relationshipLabel>Manage Data Objects</relationshipLabel>
    <relationshipName>Manage_Data_Objects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manage_Data_Users__c/Manage_Data_Users__c.object-meta.xml
<CustomObject>
    <label>Manage Data User</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Manage Data Users Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Data Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Data_Users__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Manage_Data_Group__c</referenceTo>
    <relationshipLabel>Manage Data Users</relationshipLabel>
    <relationshipName>Manage_Data_Users1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manage_Data_Users__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Inactive user.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Data_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BulkManageDataAction.cls
public without sharing class BulkManageDataAction {
    
    public class FieldInfo {
        public String fieldName { get; set; }
        public String fieldLabel { get; set; }
        public String fieldType { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static List<FieldInfo> getFieldInfo(String objectName) {
        List<FieldInfo> fieldInfoList = new List<FieldInfo>();
        
        // Describe the object
        Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(objectName);
        if (sObjectType == null) {
            throw new IllegalArgumentException('Object not found: ' + objectName);
        }
        Schema.DescribeSObjectResult describeSObjectResult = sObjectType.getDescribe();
        
        // Get the list of fields for the object
        Map<String, Schema.SObjectField> fieldsMap = describeSObjectResult.fields.getMap();
        
        for (Schema.SObjectField field : fieldsMap.values()) {
            Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
            
            FieldInfo info = new FieldInfo();
            info.fieldName = fieldDescribe.getName();
            info.fieldLabel = fieldDescribe.getLabel();
            info.fieldType = fieldDescribe.getType().name();
            
            fieldInfoList.add(info);
        }
        
        return fieldInfoList;
    }

    public static Map<String,Set<String>> getAllowedObjectsAndOperationsMap(Id userId){
        //Check if the user has the permission
        Map<String,Set<String>> getOperationsFromObjectName = new Map<String,Set<String>>();
        List<Manage_Data_Users__c> manageDataUsers = [SELECT Id,Group__c FROM Manage_Data_Users__c WHERE User__c =: userId];
        if(manageDataUsers.isEmpty()){
            return getOperationsFromObjectName;
        }
        Set<Id> groupsIds = new Set<Id>();
        for(Manage_Data_Users__c manageDataUser:manageDataUsers){
            groupsIds.add(manageDataUser.Group__c);
        }
        if(groupsIds.isEmpty()){
            return getOperationsFromObjectName;
        }

        //Create a map considering that a user can be related to multiple groups
        List<Manage_Data_Object__c> allowedObjectsAndOperations = [SELECT Id,Name,Allowed_Operations__c FROM Manage_Data_Object__c WHERE Manage_Data_Group__c IN:groupsIds];
        for(Manage_Data_Object__c manageDataObject:allowedObjectsAndOperations){
            if(getOperationsFromObjectName.containsKey(manageDataObject.Name)){
                for(String allowedOperation:manageDataObject.Allowed_Operations__c.split(';')){
                    getOperationsFromObjectName.get(manageDataObject.Name).add(allowedOperation);
                }
            } else {
                Set<String> allowedOperationsSet = new Set<String>();
                allowedOperationsSet.addAll(manageDataObject.Allowed_Operations__c.split(';'));
                getOperationsFromObjectName.put(manageDataObject.Name,allowedOperationsSet);
            }
        }
        return getOperationsFromObjectName;
    }
    
}